### ISSUE TITLE
add compatibility with all api

### ISSUE THREAD

**Issue by Lhuar** [Tcanw/GenisysPlus_Chinese#1]

**Comment by Tcanw** [comment]
Yes, this API is already compatible with all, it compatible 1.12.0 to 4.0.0

**Comment by Lhuar** [comment]
![g](https://user-images.githubusercontent.com/30007202/28039454-fd971f2a-6587-11e7-886c-273b5f99f315.jpg)
Maybe it's because my plugins are configured with api 3.0.0-ALPHA5?

**Comment by Tcanw** [comment]
yes, this can't compatible with the API with "-ALPHA"

**Comment by Tcanw** [comment]
Next version I will add English for server face

**Comment by Tcanw** [comment]
Next version I will add English language for server face

**Comment by Lhuar** [comment]
ok thanks
